Tutorial/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Tutorial.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # use namespace to indentify the app for template url 
    url(r'^polls/', include('polls.urls', namespace="polls")),
    # include() references the given urlsConf and passes only of the rest of the url string
    url(r'^admin/', include(admin.site.urls)),
)


# /polls/index/3 hits here first
# it matches the first url, which then calls polls.urls with shortend /index/3

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    # url(r'^$', views. index, name='index'),
    url(r'^index', views.IndexView.as_view(), name='index'),
    # url(r'^twoInd', views.index2, name='indexTwo'),
    url(r'(?P<pk>\d+)/vote$', views.VoteView.as_view(), name='vote'),
    url(r'(?P<pk>\d+)$', views.ResultsView.as_view(), name='results'),
    url(r'(?P<poll_id>\d+)/voted$', views.voted, name='voted')
)

#TODO do urls for detail, result, vote

"""
If your view method takes more than the "request" parameter you
can assign values to the other parameters using "kwargs" as a dictionary,
where the parameter is a "key" and the value is the "key:value".

For example:

In views.py
def sample(request,foo):
    return HttpResponse("Hello %d" % foo)

In urls.py in your app
urlpatterns = patterns('',
    url(r'^$', views.sample, name='sample', kwargs = {"foo":1}))

"""



"""
Regular Expressions:
start with r''
^string1 : the input has to start with string1
string1$ : the input has to end with string1
\d+ : the input can be multiple digits
?P<useThisVariableLater>\d+ : any digits given in input
                 will be saved in useThisVariableLater
() :captures the text that needs to be matched and sends it as an
    argument to the view 
"""

newApp/models.py
from django.db import models

# Create your models here.
from django.db import models
import datetime
from django.utils import timezone

class Author(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField(default=0) 

    # whenever an Author object is printed 
    def __unicode__(self):
        return self.name

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Author(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField(default=0) 

    # whenever an Author object is printed 
    def __unicode__(self):
        return self.name


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(Author)

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        return timezone.now() > self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    # sorting self defined methods is not support, this is workaround
    # if you try to sort by was_published .. it will sort by pub_date
    was_published_recently.admin_order_field = 'pub_date'  
    was_published_recently.short_description = "Published recently?" #changes name of header from function name to defined string
    was_published_recently.boolean = True 


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField('choice', max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return "%s   votes:%s   quest:%s" %(self.choice_text, self.votes, self.poll.question)

newApp/views.py
# Create your views here.

polls/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from polls.models import Choice, Poll

from django.views import generic 



# First option to render a page, Second option: render()
# from django.http import Http404
from django.http import HttpResponse
# from django.template import RequestContext, loader

    # template = loader.get_template('polls/index.html')
    # context = RequestContext(request, {'poll_list':latest_poll_list})
    # return HttpResponse(template.render(context))
from polls.models import Poll, Author, Choice

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "poll_list"

    def get_queryset(self):
        return Poll.objects.order_by('pub_date')[:4]


# def index2(request):
#     return HttpResponse("Hello, second world. You're at the poll index.")

class VoteView(generic.DetailView):
    # long version of get_object_or_404
    # try:
    #     currentPoll = Poll.objects.get(pk=poll_id)
    # except Poll.DoesNotExist:
    #     raise Http404

    # get_object_or_404
    # currentPoll = get_object_or_404(Poll, pk=poll_id)
    # return render(request, "polls/vote.html", {"poll": currentPoll})

    # use django.views.generic.DetailView
    model = Poll
    template_name = "polls/vote.html"

class ResultsView(generic.DetailView):
    model = Poll
    template_name = "polls/results.html"


def voted(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/vote.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', kwargs={"pk":p.id}))

newApp/templates/newApp/base_site.html
<!-- copied from /Library/Python/2.7/site-packages/django/contrib/admin/templates/admin/base_site.html -->

{% extends "admin/base.html" %}
{% load i18n %}

{% block title %}{{ title }} | {% trans 'Django site admin' %}{% endblock %}

{% block branding %}
<h1 id="site-name">{% trans 'New App Administrator' %}</h1>
{% endblock %}

{% block nav-global %}{% endblock %}

polls/templates/polls/index.html
￼{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if poll_list %}
    <ul>
    {% for poll in poll_list %}
        <!-- hardcoded link: -->
        <!-- <li><a href="/polls/{{ poll.id }}/vote">{{ poll.question }}</a></li>  -->
       <!-- use the namespace poll defined in myProject.urls.py
            use the name vote defined in myApp.urls.py -->
        <li><a href="{% url 'polls:vote' poll.id%}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:vote' poll.id %}">Vote again?</a>

polls/templates/polls/vote.html
<!-- Template poll checks first for a dictionary keyword, then for an object attribute
and then for a list element with the dot operator -->
<h1>{{poll.question}}</h1>

<!-- <ul> -->
<!-- {% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->

<!-- gets passed in if the form submit was faulty, see views.vote()-->
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}



<form action="{% url 'polls:voted' poll.id %}" method="post">
<!-- use to avoid cross site request forgeries -->
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>